import SwiftUI

// MARK: - Strategy Builder View

struct StrategyBuilderView: View {
    @StateObject private var viewModel: StrategyBuilderViewModel
    @Environment(\.dismiss) private var dismiss

    init(
        spotPrice: Double,
        strikeInterval: Double,
        lotSize: Int,
        expiryDate: Date,
        optionChain: [OptionChainRow]
    ) {
        _viewModel = StateObject(wrappedValue: StrategyBuilderViewModel(
            spotPrice: spotPrice,
            strikeInterval: strikeInterval,
            lotSize: lotSize,
            expiryDate: expiryDate,
            optionChain: optionChain
        ))
    }

    var body: some View {
        NavigationView {
            ScrollView {
                VStack(spacing: 16) {
                    // Legs Builder
                    LegsBuilderCard(viewModel: viewModel)

                    // Payoff Diagram
                    if let payoffData = viewModel.payoffData {
                        PayoffDiagramView(
                            payoffData: payoffData,
                            spotPrice: viewModel.currentSpotPrice,
                            breakevens: payoffData.breakevens,
                            touchedPrice: $viewModel.touchedPrice,
                            touchedPayoff: $viewModel.touchedPayoff
                        )
                    } else {
                        PayoffPlaceholder()
                    }

                    // Analysis Summary
                    if let payoffData = viewModel.payoffData {
                        AnalysisSummaryCard(
                            payoffData: payoffData,
                            analysis: viewModel.analysis,
                            strategy: viewModel.strategy
                        )
                    }

                    Spacer(minLength: 100)
                }
                .padding()
            }
            .background(Theme.background.ignoresSafeArea())
            .navigationTitle("Strategy Builder")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark")
                            .font(.body)
                            .foregroundColor(Theme.textSecondary)
                    }
                }

                ToolbarItem(placement: .navigationBarTrailing) {
                    Menu {
                        Button(action: { viewModel.resetToTemplate() }) {
                            Label("Reset to Template", systemImage: "arrow.counterclockwise")
                        }

                        Button(action: { viewModel.clearAllLegs() }) {
                            Label("Clear All Legs", systemImage: "trash")
                        }

                        Divider()

                        Button(action: { shareStrategy() }) {
                            Label("Share Strategy", systemImage: "square.and.arrow.up")
                        }
                    } label: {
                        Image(systemName: "ellipsis.circle")
                            .font(.body)
                            .foregroundColor(Theme.textSecondary)
                    }
                }
            }
            .sheet(isPresented: $viewModel.showStrategySelector) {
                StrategyTypeSelectorView(
                    selectedType: $viewModel.selectedStrategyType,
                    isPresented: $viewModel.showStrategySelector
                )
                .onDisappear {
                    if viewModel.selectedStrategyType != viewModel.strategy.type {
                        viewModel.selectStrategyType(viewModel.selectedStrategyType)
                    }
                }
            }
        }
    }

    // MARK: - Private Methods

    private func shareStrategy() {
        guard viewModel.isStrategyValid else { return }

        var shareText = "Option Strategy: \(viewModel.strategy.name)\n\n"
        shareText += "Legs:\n"
        for leg in viewModel.strategy.legs {
            shareText += "• \(leg.shortDescription) @ ₹\(leg.displayPremium)\n"
        }
        shareText += "\n\(viewModel.strategy.displayNetPremium)\n"

        if let payoffData = viewModel.payoffData {
            shareText += "Max Profit: \(payoffData.displayMaxProfit)\n"
            shareText += "Max Loss: \(payoffData.displayMaxLoss)\n"

            if !payoffData.breakevens.isEmpty {
                shareText += "Breakevens: \(payoffData.breakevens.map { String(format: "%.0f", $0) }.joined(separator: ", "))\n"
            }
        }

        shareText += "\nGenerated by Optix"

        let activityVC = UIActivityViewController(
            activityItems: [shareText],
            applicationActivities: nil
        )

        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let rootVC = windowScene.windows.first?.rootViewController {
            rootVC.present(activityVC, animated: true)
        }
    }
}

// MARK: - Payoff Placeholder

private struct PayoffPlaceholder: View {
    var body: some View {
        VStack(spacing: 12) {
            Image(systemName: "chart.line.uptrend.xyaxis")
                .font(.system(size: 40))
                .foregroundColor(Theme.textMuted)

            Text("Add legs to see payoff diagram")
                .font(.subheadline)
                .foregroundColor(Theme.textSecondary)
        }
        .frame(maxWidth: .infinity)
        .frame(height: 200)
        .background(Theme.card)
        .cornerRadius(16)
    }
}

// MARK: - Strategy Builder FAB

struct StrategyBuilderFAB: View {
    let action: () -> Void

    var body: some View {
        Button(action: {
            let generator = UIImpactFeedbackGenerator(style: .medium)
            generator.impactOccurred()
            action()
        }) {
            HStack(spacing: 8) {
                Image(systemName: "square.stack.3d.up.fill")
                    .font(.body)
                Text("Build Strategy")
                    .font(.subheadline)
                    .fontWeight(.semibold)
            }
            .foregroundColor(Theme.textPrimary)
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(
                LinearGradient(
                    colors: [Theme.accentBlue, Theme.accentPurple],
                    startPoint: .leading,
                    endPoint: .trailing
                )
            )
            .cornerRadius(25)
            .shadow(color: Theme.accentBlue.opacity(0.4), radius: 8, x: 0, y: 4)
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Preview

#Preview {
    StrategyBuilderView(
        spotPrice: 24000,
        strikeInterval: 50,
        lotSize: 25,
        expiryDate: Date().addingTimeInterval(7 * 24 * 60 * 60),
        optionChain: []
    )
    
}
